name: busy
description: A flutter package that focuses on the busy state. Centralize the management of the loading widget, thanks to this very easy-to-use package, which uses no external package dependencies.
version: 1.0.1
homepage: https://github.com/gdaguin/busy

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  lints: ^2.1.1

flutter:
  uses-material-design: true