name: busy
description: A flutter package that focuses on the busy state.
version: 1.0.0
homepage: https://github.com/gdaguin/busy

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true